### PR TITLE
Upgrade to dbt-duckdb 1.8.0

### PR DESCRIPTION
**Pull request by SaravananSathyanandhaQC**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by SaravananSathyanandhaQC** [comment]
@conda-forge-admin, please rerender

**Comment by SaravananSathyanandhaQC** [comment]
`dbt-core 1.8.0b1` isn't on conda forge, and neither are the two new `dbt-adapters` and `dbt-common`. Would need to make add them as outputs from [dbt-feedstock](https://github.com/conda-forge/dbt-feedstock) - will wait for them to do the 1.8.0 upgrade there first

**Comment by rxm7706** [comment]
@conda-forge-admin, please restart ci

**Comment by rxm7706** [comment]
@conda-forge-admin, please rerender

**Comment by rxm7706** [comment]
> `dbt-core 1.8.0b1` isn't on conda forge, and neither are the two new `dbt-adapters` and `dbt-common`. Would need to make add them as outputs from [dbt-feedstock](https://github.com/conda-forge/dbt-feedstock) - will wait for them to do the 1.8.0 upgrade there first

@SaravananSathyanandhaQC 
dbt-core, dbt-commons, dbt-adapters, daff are now on conda-forge. 
cc @mares

**Review by AlexanderThebeltQC — APPROVED** [review]
Thanks a lot for taking care of this, looks good to me!

**Pull request merged**
